# Generated by Django 5.0.1 on 2024-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_phone_number_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
