# Generated by Django 5.0.1 on 2024-11-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_evaluationcriteria_remove_evaluation_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_registration_open', models.BooleanField(default=True)),
                ('evaluation_registration_open', models.BooleanField(default=True)),
                ('coordinator_registration_open', models.BooleanField(default=True)),
            ],
        ),
    ]
